REVIEW_PROMPT_TEMPLATE = """Review the generated HTML below and fix any violations of the design rules.
CRITICAL: You MUST also preserve and correctly apply the user's original request parameters and custom requests. Do NOT remove or revert any custom layout/style changes requested by the user.

[USER'S ORIGINAL REQUEST]
- Title: {title}
- Custom Requests / Description: {description}

[DESIGN RULES]
1. CRITICAL: The outermost wrapper MUST have `padding: 0;`. Remove any other padding on it.
2. CRITICAL: DO NOT include instructional texts in parentheses (e.g. `(Draw a line)`).
3. Ensure text inside boxes is vertically centered using `display: flex; align-items: center; justify-content: center;`.
4. CRITICAL: NEVER use literal underscores (`__________`) for blank spaces! Remove them entirely. Instead, use a flex container with `border-bottom` for the blank area. The underline element MUST contain a non-breaking space: `<div class="underline">&nbsp;</div>` to force baseline alignment in WeasyPrint.
5. CRITICAL: Ensure `overflow: hidden;` is applied to all boxes and cells so text doesn't spill out. DO NOT use `white-space: nowrap;` on large sections.
6. CRITICAL: For text label + blank line rows, DO NOT hardcode widths. Use `white-space: nowrap;` on the label, and `flex: 1; border-bottom: 1px solid #333;` on the blank area. The blank area (underline) MUST contain a non-breaking space `&nbsp;`. The parent container MUST have `align-items: baseline;` to ensure perfect vertical alignment.
7. CRITICAL: To prevent double-thick (2px) borders, do NOT use generic border: 1px solid ... on all cells. Let the wrapper container have border-top and border-left, and let inner cells/rows only have border-right and border-bottom.
7a. CRITICAL: Do NOT remove the right or bottom borders of the cells on the edges (do NOT use `:nth-child` to set `border-right: none` or `border-bottom: none`). The cells' right/bottom borders must remain to form the right/bottom outer edges of the grid, ensuring the entire grid border is completely closed.
7b. CRITICAL: For Weekly Planners or Calendars, do NOT use generic placeholders like 'DAY 1', 'DAY 2', or 'Day {{i+1}}'. Write the actual day names (e.g. 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN') manually.
7c. CRITICAL: Ensure the top-right corner of the outer border is completely closed. If the Title is borderless, place it OUTSIDE the bordered grid container. Do not apply border-top/left to a container that includes a borderless title and leaves the top-right side open.
7d. CRITICAL: For Mandalart, to ensure all inner grid lines are visible and symmetric, the sub-grid container (class="sub-grid") MUST have `border-top: 1px solid <color>; border-left: 1px solid <color>;` and sub-cells (class="sub-cell") MUST have `border-right: 1px solid <color>; border-bottom: 1px solid <color>;` where the border colors match exactly (e.g., `#ccc` / `#e5e7eb` in normal modes, or `#333` in guide mode). NEVER remove or hide borders on any edge sub-cells using :last-child or :nth-child resets.
7e. CRITICAL: For Calendars, do NOT write hardcoded date numbers (1, 2, 3...) inside the grid cells unless explicitly requested. Leave date cells completely blank.
7f. CRITICAL: Do NOT write code expressions like `split(",")` or array indexing in HTML text content (e.g. `MON,TUE...split(",")[0]` is strictly forbidden). HTML text must be plain text. If you need distinct text values for repeating blocks (like day names), write each block manually without using the `<repeat>` macro.
7g. CRITICAL: For Daily Planners, do NOT hardcode absolute pixel heights on timetable slots (e.g. do NOT use height: 40px; on slots). Slots must use flex: 1; so they stretch and fill the timetable column, ensuring the bottom of the timetable is closed with the last slot's bottom border.
7h. CRITICAL: Ensure the Notes/Memo area (`.lined-bg`) is never left open at the top. If the block above it has no bottom border, or if there is margin between them, the Notes block MUST have its own top border or the parent wrapper must close it.
7i. CRITICAL: Ensure visual breathing room (Negative Space). If sections are too tight, verify row gaps and margins. Check font sizes for a clean typography hierarchy. Use subtle dotted/dashed lines for secondary grids or circular checklists for Cute theme where appropriate.
7j. CRITICAL: Column Height Alignment. For multi-column layouts, verify if the bottom lines of adjacent columns match. Use `align-items: stretch` on the parent and `height: 100%` on children to sync heights.
7k. CRITICAL: Margin Unity. Ensure all padding, margins, and gaps use uniform modular spacing (8px/12px/16px/20px multiples) to establish a clean vertical rhythm. For multi-card templates, prefer 12px spacing to prevent vertical page overflow.
7l. CRITICAL: Bullet/Digit Axis. Verify if vertical checklists or timetables have fixed width columns for numbers/icons (e.g. `width: 40px` or `width: 50px`) to prevent horizontal layout shift and ensure vertical axis alignment.
7m. CRITICAL: For the main page header, DO NOT use a background banner container (`class="header-block"`). Instead, use a clean, bannerless flex row (`display: flex; justify-content: space-between; align-items: flex-end;`) where the Title is on the left and the Metadata fields are on the right.
7n. CRITICAL: Inside the metadata container, EACH metadata field (label and input line) MUST be wrapped together in a single flex container (e.g., `class="meta-item"` or `class="meta-field"`). The underline element MUST contain `&nbsp;` (e.g., `<div class="underline">&nbsp;</div>`). Within the flex container, apply `align-items: baseline` so the text label and underline align perfectly on the same vertical level and move together.
7o. CRITICAL: Header-Grid Width Alignment. The page header container, the main grid container, and all grid rows MUST have `width: 100%; box-sizing: border-box;` explicitly styled. Verify that the rightmost edge of the metadata field aligns perfectly with the rightmost edge of the grid, and does not exceed or overflow it.
7p. CRITICAL: For independent, non-adjacent content cards or modules (e.g., class="card", Key Summary, Memorable Quotes, Personal Thoughts) that are spaced out and do not share adjacent edges, you MUST use all 4 borders closed (e.g., `border: 1px solid #333;` or `border: 1px solid #ccc;` depending on style) to form a complete box. Do NOT use unidirectional borders (e.g., only right/bottom) for these.
7q. CRITICAL: Do NOT use empty CSS divs (like `<div class="circle"></div>` without text) for rating scales or checkbox circles. WeasyPrint collapses empty elements, throwing their position off. You MUST either use text characters (e.g., `○` or `★`/`☆`) or ensure any CSS circle/box div contains a non-breaking space: `<div class="circle">&nbsp;</div>`, has `flex: none;` (or `flex-shrink: 0;`) and `box-sizing: border-box;` to prevent horizontal squashing, and is wrapped in a flex container with `align-items: center` or `align-items: baseline` to align correctly with text/labels.
7r. CRITICAL: Do NOT use `height: 100%` on child elements inside a flex container (e.g., `.lined-bg` inside `.card` or `.card` inside `.planner-wrapper`) when you want them to fill the remaining vertical space. Instead, use `flex-grow: 1;` or `flex: 1; min-height: 0;`. Using `height: 100%` on a flex child ignores sibling heights and parent padding, causing elements to overflow and cut off at the bottom of the page.
7s. CRITICAL: For Mandalart, to prevent WeasyPrint from collapsing the nested 3x3 grids and squashing sub-cells into the right edge, you MUST style the sub-cells (class="sub-cell") with `flex: 0 0 33.333%; width: 33.333%; box-sizing: border-box;`, the sub-rows (class="sub-row") with `display: flex; flex-direction: row; width: 100%; flex: 1;`, the sub-grid (class="sub-grid") with `flex-grow: 1; width: 100%;` (do NOT use height: 100%), and the outer cells (class="cell") with `display: flex; flex-direction: column;`.
7t. CRITICAL: For Reading Note or Book Review metadata cards: the metadata fields (Book Title, Author, Genre, Rating) MUST either be stacked vertically (each occupying a full-width row) or laid out in equal-width flex columns (e.g., using class="col" with flex: 1). DO NOT mix flex-growing text fields and rating circles in the same flex row without equal-width column wrappers, as this will push rating circles off the page.
7u. CRITICAL: For templates containing 3 or more independent cards or note sections (e.g., Key Summary, Memorable Quotes, Personal Thoughts), you MUST budget space conservatively to prevent vertical page overflow/clipping: use smaller min-heights for lined backgrounds (e.g., min-height: 60px to 80px) and compact paddings/margins (e.g., padding: 10px to 15px, margin-bottom: 10px to 15px).
7v. CRITICAL: Avoid spacing duplication. When using `gap` on a flex container (e.g., planner-wrapper, card, or row), you MUST NOT use margins (`margin-top` or `margin-bottom`) on its child elements in the same direction, as WeasyPrint does not collapse margins with flex gaps. This causes spacing to double and will push content off the bottom of the page.
7w. CRITICAL: Always set a reasonable line-height (e.g., `line-height: 1.3;` or `line-height: 1.4;`) globally or on the body. Handwriting/cursive fonts (like 'Patrick Hand' or 'Nanum Pen Script') have extremely large font metrics, which causes WeasyPrint to evaluate their default line-height as 50px+ and push content off the page. Setting an explicit line-height resolves this.
8. CRITICAL: Replace `white-space: nowrap;` on the main Title with `word-break: keep-all; overflow-wrap: normal;` so words wrap at spaces but do not break in the middle of a word.
{dynamic_rules}
Generated HTML:
```html
{html_content}
```
Return ONLY the corrected HTML/CSS. No explanations.
"""
