REVIEW_PROMPT_TEMPLATE = """Review the generated HTML below and fix any violations of the design rules.
CRITICAL: You MUST also preserve and correctly apply the user's original request parameters and custom requests. Do NOT remove or revert any custom layout/style changes requested by the user.

[USER'S ORIGINAL REQUEST]
- Title: {title}
- Custom Requests / Description: {description}

[DESIGN RULES]
1. CRITICAL: The outermost wrapper MUST have `padding: 0;`. Remove any other padding on it.
2. CRITICAL: DO NOT include instructional texts in parentheses (e.g. `(Draw a line)`).
3. Ensure text inside boxes is vertically centered using `display: flex; align-items: center; justify-content: center;`.
4. CRITICAL: NEVER use literal underscores (`__________`) for blank spaces! Remove them entirely. Instead, use a flex container with `border-bottom` for the blank area. The underline element MUST contain a non-breaking space: `<div class="underline">&nbsp;</div>`. Verify that you have NOT applied `border-bottom: none;` or `border: none;` (even as inline styles) to any underlines or timetable rows!
5. CRITICAL: Ensure `overflow: hidden;` is applied to all boxes and cells so text doesn't spill out. DO NOT use `white-space: nowrap;` on large sections.
8. CRITICAL: The main page Title (h1 / .title) MUST always stay on a single line. ALWAYS style it with `white-space: nowrap;` to prevent it from wrapping and wasting vertical space. To prevent the title from pushing metadata out of bounds, use a compact font-size (e.g. 24px) for the title, and apply `min-width: 0;` to the metadata flex container and its `.underline` elements.
6. CRITICAL: For text label + blank line rows, DO NOT hardcode widths. Use `white-space: nowrap;` on the label, and `flex: 1; border-bottom: 1px solid #333;` on the blank area. The blank area (underline) MUST contain a non-breaking space `&nbsp;`. The parent container MUST have `align-items: baseline;` to ensure perfect vertical alignment.
7. CRITICAL: To prevent double-thick (2px) borders in Flexbox layouts, do NOT use generic border: 1px solid ... on all cells. Let the wrapper container have border-top and border-left, and let inner cells/rows only have border-right and border-bottom. Exception: For HTML tables (`<table>`) with `border-collapse: collapse` (such as Mandalart), you MUST style the table with a uniform 3px outer border on all four sides (`border: 3px solid ...`) and style the cells with a standard 1px border on all sides (`border: 1px solid ...`). The collapsed border model automatically prevents double borders and ensures a uniform outer border.
7a. CRITICAL: Do NOT remove the right or bottom borders of the cells on the edges (do NOT use `:nth-child` to set `border-right: none` or `border-bottom: none`). The cells' right/bottom borders must remain to form the right/bottom outer edges of the grid, ensuring the entire grid border is completely closed. Check multi-column layouts to ensure vertical separators (`border-right`) are NOT missing.
7b. CRITICAL: For Weekly Planners or Calendars, do NOT use generic placeholders like 'DAY 1', 'DAY 2', or 'Day {{i+1}}'. Write the actual day names (e.g. 'MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN') manually.
7c. CRITICAL: Ensure the top-right corner of the outer border is completely closed. If the Title is borderless, place it OUTSIDE the bordered grid container. Do not apply border-top/left to a container that includes a borderless title and leaves the top-right side open.
7d. CRITICAL: For Mandalart, to ensure Weasyprint does not collapse the table height, the table cells `td` MUST have an explicit height set (either `95px` to `105px` (e.g., `.mandalart-table td {{ height: 100px; }}`) if there is no bottom section, or `75px` to `80px` (e.g., `.mandalart-table td {{ height: 78px; }}`) if there is a bottom Notes/checklist card).
7e. CRITICAL: For Calendars, do NOT write hardcoded date numbers (1, 2, 3...) inside the grid cells unless explicitly requested. Leave date cells completely blank.
7f. CRITICAL: Do NOT write code expressions like `split(",")` or array indexing in HTML text content (e.g. `MON,TUE...split(",")[0]` is strictly forbidden). HTML text must be plain text. If you need distinct text values for repeating blocks (like day names), write each block manually without using the `<repeat>` macro.
7g. CRITICAL: For Daily Planners, do NOT hardcode absolute pixel heights on timetable slots (e.g. do NOT use height: 40px; on slots). Slots must use flex: 1; so they stretch and fill the timetable column, ensuring the bottom of the timetable is closed with the last slot's bottom border.
7h. CRITICAL: Ensure the Notes/Memo area (`.lined-bg`) is never left open at the top. Verify that NO `.lined-bg` tag is empty (it MUST contain `&nbsp;`) and that you did NOT generate any custom background CSS (like `background-image` or `linear-gradient`) for it.
7i. CRITICAL: Ensure visual breathing room (Negative Space). If sections are too tight, verify row gaps and margins. Check font sizes for a clean typography hierarchy. Use subtle dotted/dashed lines for secondary grids or circular checklists for Cute theme where appropriate.
7j. CRITICAL: Column Height Alignment. For multi-column layouts, verify if the bottom lines of adjacent columns match. Use `align-items: stretch` on the parent and `height: 100%` on children to sync heights.
7k. CRITICAL: Margin Unity. Ensure all padding, margins, and gaps use uniform modular spacing (8px/12px/16px/20px multiples) to establish a clean vertical rhythm. For multi-card templates, prefer 12px spacing to prevent vertical page overflow.
7l. CRITICAL: Bullet/Digit Axis. Verify if vertical checklists or timetables have fixed width columns for numbers/icons (e.g. `width: 40px` or `width: 50px`) to prevent horizontal layout shift and ensure vertical axis alignment.
7m. CRITICAL: For the main page header, DO NOT use a background banner container (`class="header-block"`). Instead, use a clean, bannerless flex row (`display: flex; justify-content: space-between; align-items: flex-end;`) where the Title is on the left and the Metadata fields are on the right.
7n. CRITICAL: Inside the metadata container, EACH metadata field (label and input line) MUST be wrapped together in a single flex container (e.g., `class="meta-item"` or `class="meta-field"`). The underline element MUST contain `&nbsp;` (e.g., `<div class="underline">&nbsp;</div>`). Within the flex container, apply `align-items: baseline` so the text label and underline align perfectly on the same vertical level and move together.
7o. CRITICAL: Header-Grid Width Alignment. The page header container, the main grid container, and all grid rows MUST have `width: 100%; box-sizing: border-box;` explicitly styled. Verify that the rightmost edge of the metadata field aligns perfectly with the rightmost edge of the grid, and does not exceed or overflow it.
7p. CRITICAL: For independent, non-adjacent content cards or modules (e.g., class="card", Key Summary, Memorable Quotes, Personal Thoughts) that are spaced out and do not share adjacent edges, you MUST use all 4 borders closed (e.g., `border: 1px solid #333;` or `border: 1px solid #ccc;` depending on style) to form a complete box. Do NOT use unidirectional borders (e.g., only right/bottom) for these.
7q. CRITICAL: Do NOT use empty CSS divs (like `<div class="circle"></div>` without text) for rating scales or checkbox circles. WeasyPrint collapses empty elements, throwing their position off. You MUST either use text characters (e.g., `○` or `★`/`☆`) or ensure any CSS circle/box div contains a non-breaking space: `<div class="circle">&nbsp;</div>`, has `flex: none;` (or `flex-shrink: 0;`) and `box-sizing: border-box;` to prevent horizontal squashing, and is wrapped in a flex container with `align-items: center` (CRITICAL: The direct parent field/row containing BOTH the text label and the circles MUST use `align-items: center`. Do NOT use `align-items: baseline` on ANY parent wrapper containing circles, otherwise WeasyPrint shifts the circles upward).
7r. CRITICAL: Do NOT use `height: 100%` on child elements inside a flex container (e.g., `.lined-bg` inside `.card` or `.card` inside `.planner-wrapper`) when you want them to fill the remaining vertical space. Instead, use `flex-grow: 1;` or `flex: 1; min-height: 0;`. Using `height: 100%` on a flex child ignores sibling heights and parent padding, causing elements to overflow and cut off at the bottom of the page. However, Metadata blocks/cards (containing Book Title, Author, Rating, etc.) MUST use `flex: none;` so they don't stretch vertically and leave empty floating space at the bottom. Only the main content cards (e.g., Key Summary, Notes) should use `flex-grow: 1;`.
7s. CRITICAL: For Mandalart, to avoid empty space at the bottom, the page must be fully utilized. Either make the table cells explicitly tall (`95px` to `105px`) so the grid fills the page, or keep the grid square (cells `75px` to `80px` high) and add a beautifully styled notes card or action checklist at the bottom (`150px` to `220px` high) to fill the remaining space cleanly. The grid must be a single 9x9 HTML table (class="mandalart-table") with thick 3px borders separating the 3x3 sub-grids. To ensure all four outer borders of the table are uniformly thick, you MUST style the table with `border: 3px solid <color>;` and style the cells (`td`) with `border: 1px solid <color>;` on all sides (never use asymmetric borders like border-top/left only on the table wrapper).
7t. CRITICAL: For Reading Note or Book Review metadata cards: the metadata fields (Book Title, Author, Genre, Rating) MUST either be stacked vertically (each occupying a full-width row) or laid out in equal-width flex columns (e.g., using class="col" with flex: 1). DO NOT mix flex-growing text fields and rating circles in the same flex row without equal-width column wrappers, as this will push rating circles off the page.
7u. CRITICAL: For templates containing 3 or more independent cards or note sections (e.g., Key Summary, Memorable Quotes, Personal Thoughts), you MUST budget space conservatively to prevent vertical page overflow/clipping: use smaller min-heights for lined backgrounds (e.g., min-height: 60px to 80px) and compact paddings/margins (e.g., padding: 10px to 15px, margin-bottom: 10px to 15px).
7v. CRITICAL: Avoid spacing duplication. When using `gap` on a flex container (e.g., planner-wrapper, card, or row), you MUST NOT use margins (`margin-top` or `margin-bottom`) on its child elements in the same direction, as WeasyPrint does not collapse margins with flex gaps. This causes spacing to double and will push content off the bottom of the page.
7w. CRITICAL: Always set a reasonable line-height (e.g., `line-height: 1.3;` or `line-height: 1.4;`) globally or on the body. Handwriting/cursive fonts (like 'Patrick Hand' or 'Nanum Pen Script') have extremely large font metrics, which causes WeasyPrint to evaluate their default line-height as 50px+ and push content off the page. Setting an explicit line-height resolves this.

{dynamic_rules}
Generated HTML:
```html
{html_content}
```
Return ONLY the corrected HTML/CSS. No explanations.
"""
